/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

package org.opensearch.ml.utils;

public class TestData {

    public static final String IRIS_DATA = "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.1,\"sepal_width_in_cm\":3.5,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.9,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.7,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":1.3,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.6,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.0,\"sepal_width_in_cm\":3.6,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.4,\"sepal_width_in_cm\":3.9,\"petal_length_in_cm\":1.7,\"petal_width_in_cm\":0.4,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.6,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.3,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.0,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.4,\"sepal_width_in_cm\":2.9,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.9,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.1,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.4,\"sepal_width_in_cm\":3.7,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.8,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":1.6,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.8,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.1,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.3,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":1.1,\"petal_width_in_cm\":0.1,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.8,\"sepal_width_in_cm\":4.0,\"petal_length_in_cm\":1.2,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.7,\"sepal_width_in_cm\":4.4,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.4,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.4,\"sepal_width_in_cm\":3.9,\"petal_length_in_cm\":1.3,\"petal_width_in_cm\":0.4,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.1,\"sepal_width_in_cm\":3.5,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.3,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.7,\"sepal_width_in_cm\":3.8,\"petal_length_in_cm\":1.7,\"petal_width_in_cm\":0.3,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.1,\"sepal_width_in_cm\":3.8,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.3,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.4,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":1.7,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.1,\"sepal_width_in_cm\":3.7,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.4,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.6,\"sepal_width_in_cm\":3.6,\"petal_length_in_cm\":1.0,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.1,\"sepal_width_in_cm\":3.3,\"petal_length_in_cm\":1.7,\"petal_width_in_cm\":0.5,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.8,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":1.9,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.0,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":1.6,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.0,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":1.6,\"petal_width_in_cm\":0.4,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.2,\"sepal_width_in_cm\":3.5,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.2,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.7,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":1.6,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.8,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":1.6,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.4,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.4,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.2,\"sepal_width_in_cm\":4.1,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.1,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.5,\"sepal_width_in_cm\":4.2,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.9,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.1,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.0,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":1.2,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.5,\"sepal_width_in_cm\":3.5,\"petal_length_in_cm\":1.3,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.9,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.1,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.4,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":1.3,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.1,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.0,\"sepal_width_in_cm\":3.5,\"petal_length_in_cm\":1.3,\"petal_width_in_cm\":0.3,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.5,\"sepal_width_in_cm\":2.3,\"petal_length_in_cm\":1.3,\"petal_width_in_cm\":0.3,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.4,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":1.3,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.0,\"sepal_width_in_cm\":3.5,\"petal_length_in_cm\":1.6,\"petal_width_in_cm\":0.6,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.1,\"sepal_width_in_cm\":3.8,\"petal_length_in_cm\":1.9,\"petal_width_in_cm\":0.4,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.8,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.3,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.1,\"sepal_width_in_cm\":3.8,\"petal_length_in_cm\":1.6,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.6,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.3,\"sepal_width_in_cm\":3.7,\"petal_length_in_cm\":1.5,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.0,\"sepal_width_in_cm\":3.3,\"petal_length_in_cm\":1.4,\"petal_width_in_cm\":0.2,\"class\":\"Iris-setosa\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.0,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":4.7,\"petal_width_in_cm\":1.4,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.4,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":4.5,\"petal_width_in_cm\":1.5,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.9,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":4.9,\"petal_width_in_cm\":1.5,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.5,\"sepal_width_in_cm\":2.3,\"petal_length_in_cm\":4.0,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.5,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":4.6,\"petal_width_in_cm\":1.5,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.7,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":4.5,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.3,\"sepal_width_in_cm\":3.3,\"petal_length_in_cm\":4.7,\"petal_width_in_cm\":1.6,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.9,\"sepal_width_in_cm\":2.4,\"petal_length_in_cm\":3.3,\"petal_width_in_cm\":1.0,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.6,\"sepal_width_in_cm\":2.9,\"petal_length_in_cm\":4.6,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.2,\"sepal_width_in_cm\":2.7,\"petal_length_in_cm\":3.9,\"petal_width_in_cm\":1.4,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.0,\"sepal_width_in_cm\":2.0,\"petal_length_in_cm\":3.5,\"petal_width_in_cm\":1.0,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.9,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":4.2,\"petal_width_in_cm\":1.5,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.0,\"sepal_width_in_cm\":2.2,\"petal_length_in_cm\":4.0,\"petal_width_in_cm\":1.0,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.1,\"sepal_width_in_cm\":2.9,\"petal_length_in_cm\":4.7,\"petal_width_in_cm\":1.4,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.6,\"sepal_width_in_cm\":2.9,\"petal_length_in_cm\":3.6,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.7,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":4.4,\"petal_width_in_cm\":1.4,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.6,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":4.5,\"petal_width_in_cm\":1.5,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.8,\"sepal_width_in_cm\":2.7,\"petal_length_in_cm\":4.1,\"petal_width_in_cm\":1.0,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.2,\"sepal_width_in_cm\":2.2,\"petal_length_in_cm\":4.5,\"petal_width_in_cm\":1.5,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.6,\"sepal_width_in_cm\":2.5,\"petal_length_in_cm\":3.9,\"petal_width_in_cm\":1.1,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.9,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":4.8,\"petal_width_in_cm\":1.8,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.1,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":4.0,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.3,\"sepal_width_in_cm\":2.5,\"petal_length_in_cm\":4.9,\"petal_width_in_cm\":1.5,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.1,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":4.7,\"petal_width_in_cm\":1.2,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.4,\"sepal_width_in_cm\":2.9,\"petal_length_in_cm\":4.3,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.6,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":4.4,\"petal_width_in_cm\":1.4,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.8,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":4.8,\"petal_width_in_cm\":1.4,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.7,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":5.0,\"petal_width_in_cm\":1.7,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.0,\"sepal_width_in_cm\":2.9,\"petal_length_in_cm\":4.5,\"petal_width_in_cm\":1.5,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.7,\"sepal_width_in_cm\":2.6,\"petal_length_in_cm\":3.5,\"petal_width_in_cm\":1.0,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.5,\"sepal_width_in_cm\":2.4,\"petal_length_in_cm\":3.8,\"petal_width_in_cm\":1.1,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.5,\"sepal_width_in_cm\":2.4,\"petal_length_in_cm\":3.7,\"petal_width_in_cm\":1.0,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.8,\"sepal_width_in_cm\":2.7,\"petal_length_in_cm\":3.9,\"petal_width_in_cm\":1.2,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.0,\"sepal_width_in_cm\":2.7,\"petal_length_in_cm\":5.1,\"petal_width_in_cm\":1.6,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.4,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":4.5,\"petal_width_in_cm\":1.5,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.0,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":4.5,\"petal_width_in_cm\":1.6,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.7,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":4.7,\"petal_width_in_cm\":1.5,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.3,\"sepal_width_in_cm\":2.3,\"petal_length_in_cm\":4.4,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.6,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":4.1,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.5,\"sepal_width_in_cm\":2.5,\"petal_length_in_cm\":4.0,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.5,\"sepal_width_in_cm\":2.6,\"petal_length_in_cm\":4.4,\"petal_width_in_cm\":1.2,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.1,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":4.6,\"petal_width_in_cm\":1.4,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.8,\"sepal_width_in_cm\":2.6,\"petal_length_in_cm\":4.0,\"petal_width_in_cm\":1.2,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.0,\"sepal_width_in_cm\":2.3,\"petal_length_in_cm\":3.3,\"petal_width_in_cm\":1.0,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.6,\"sepal_width_in_cm\":2.7,\"petal_length_in_cm\":4.2,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.7,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":4.2,\"petal_width_in_cm\":1.2,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.7,\"sepal_width_in_cm\":2.9,\"petal_length_in_cm\":4.2,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.2,\"sepal_width_in_cm\":2.9,\"petal_length_in_cm\":4.3,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.1,\"sepal_width_in_cm\":2.5,\"petal_length_in_cm\":3.0,\"petal_width_in_cm\":1.1,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.7,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":4.1,\"petal_width_in_cm\":1.3,\"class\":\"Iris-versicolor\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.3,\"sepal_width_in_cm\":3.3,\"petal_length_in_cm\":6.0,\"petal_width_in_cm\":2.5,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.8,\"sepal_width_in_cm\":2.7,\"petal_length_in_cm\":5.1,\"petal_width_in_cm\":1.9,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.1,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":5.9,\"petal_width_in_cm\":2.1,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.3,\"sepal_width_in_cm\":2.9,\"petal_length_in_cm\":5.6,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.5,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":5.8,\"petal_width_in_cm\":2.2,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.6,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":6.6,\"petal_width_in_cm\":2.1,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":4.9,\"sepal_width_in_cm\":2.5,\"petal_length_in_cm\":4.5,\"petal_width_in_cm\":1.7,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.3,\"sepal_width_in_cm\":2.9,\"petal_length_in_cm\":6.3,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.7,\"sepal_width_in_cm\":2.5,\"petal_length_in_cm\":5.8,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.2,\"sepal_width_in_cm\":3.6,\"petal_length_in_cm\":6.1,\"petal_width_in_cm\":2.5,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.5,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":5.1,\"petal_width_in_cm\":2.0,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.4,\"sepal_width_in_cm\":2.7,\"petal_length_in_cm\":5.3,\"petal_width_in_cm\":1.9,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.8,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":5.5,\"petal_width_in_cm\":2.1,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.7,\"sepal_width_in_cm\":2.5,\"petal_length_in_cm\":5.0,\"petal_width_in_cm\":2.0,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.8,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":5.1,\"petal_width_in_cm\":2.4,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.4,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":5.3,\"petal_width_in_cm\":2.3,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.5,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":5.5,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.7,\"sepal_width_in_cm\":3.8,\"petal_length_in_cm\":6.7,\"petal_width_in_cm\":2.2,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.7,\"sepal_width_in_cm\":2.6,\"petal_length_in_cm\":6.9,\"petal_width_in_cm\":2.3,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.0,\"sepal_width_in_cm\":2.2,\"petal_length_in_cm\":5.0,\"petal_width_in_cm\":1.5,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.9,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":5.7,\"petal_width_in_cm\":2.3,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.6,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":4.9,\"petal_width_in_cm\":2.0,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.7,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":6.7,\"petal_width_in_cm\":2.0,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.3,\"sepal_width_in_cm\":2.7,\"petal_length_in_cm\":4.9,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.7,\"sepal_width_in_cm\":3.3,\"petal_length_in_cm\":5.7,\"petal_width_in_cm\":2.1,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.2,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":6.0,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.2,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":4.8,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.1,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":4.9,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.4,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":5.6,\"petal_width_in_cm\":2.1,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.2,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":5.8,\"petal_width_in_cm\":1.6,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.4,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":6.1,\"petal_width_in_cm\":1.9,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.9,\"sepal_width_in_cm\":3.8,\"petal_length_in_cm\":6.4,\"petal_width_in_cm\":2.0,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.4,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":5.6,\"petal_width_in_cm\":2.2,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.3,\"sepal_width_in_cm\":2.8,\"petal_length_in_cm\":5.1,\"petal_width_in_cm\":1.5,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.1,\"sepal_width_in_cm\":2.6,\"petal_length_in_cm\":5.6,\"petal_width_in_cm\":1.4,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":7.7,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":6.1,\"petal_width_in_cm\":2.3,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.3,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":5.6,\"petal_width_in_cm\":2.4,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.4,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":5.5,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.0,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":4.8,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.9,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":5.4,\"petal_width_in_cm\":2.1,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.7,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":5.6,\"petal_width_in_cm\":2.4,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.9,\"sepal_width_in_cm\":3.1,\"petal_length_in_cm\":5.1,\"petal_width_in_cm\":2.3,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.8,\"sepal_width_in_cm\":2.7,\"petal_length_in_cm\":5.1,\"petal_width_in_cm\":1.9,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.8,\"sepal_width_in_cm\":3.2,\"petal_length_in_cm\":5.9,\"petal_width_in_cm\":2.3,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.7,\"sepal_width_in_cm\":3.3,\"petal_length_in_cm\":5.7,\"petal_width_in_cm\":2.5,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.7,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":5.2,\"petal_width_in_cm\":2.3,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.3,\"sepal_width_in_cm\":2.5,\"petal_length_in_cm\":5.0,\"petal_width_in_cm\":1.9,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.5,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":5.2,\"petal_width_in_cm\":2.0,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":6.2,\"sepal_width_in_cm\":3.4,\"petal_length_in_cm\":5.4,\"petal_width_in_cm\":2.3,\"class\":\"Iris-virginica\"}\n"
        + "{ \"index\" : { \"_index\" : \"iris_data\" } }\n"
        + "{\"sepal_length_in_cm\":5.9,\"sepal_width_in_cm\":3.0,\"petal_length_in_cm\":5.1,\"petal_width_in_cm\":1.8,\"class\":\"Iris-virginica\"}\n";
}
