name: "Pull Request Labeler"
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: 22958780
      - name: Label
        uses: actions/labeler@v4
        with:
          repo-token: ${{ steps.github_app_token.outputs.token }}
